[package]
name = "adzuki-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]
name = "shared"

[dependencies]
crux_core.workspace = true
facet = "0.46.5"
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
crux_core = { workspace = true, features = ["testing"] }
